<?php

namespace App\Controller\Admin;

use App\Entity\Electricity;
use EasyCorp\Bundle\EasyAdminBundle\Config\Crud;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController;
use EasyCorp\Bundle\EasyAdminBundle\Field\DateField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextEditorField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TimeField;

class ElectricityCrudController extends AbstractCrudController
{
    public static function getEntityFqcn(): string
    {
        return Electricity::class;
    }


    public function configureFields(string $pageName): iterable
    {
        return [
            DateField::new('created', 'Fecha creación')->setFormat('dd-MM-y'),
            TextField::new('address', 'Punto de trabajo'),
            TimeField::new('start_time', 'Hora de inicio')->setFormat('HH:mm'),
            TimeField::new('end_time', 'Hora de fín')->setFormat('HH:mm'),
            TextEditorField::new('description', 'Descripción'),
        ];
    }

/*    public function configureCrud(Crud $crud): Crud
    {
        return $crud->setDateFormat('long')->setTimeFormat('medium');

        //return parent::configureCrud($crud); // TODO: Change the autogenerated stub
    }*/

    public function configureCrud(Crud $crud): Crud
    {
        return $crud
            ->setEntityLabelInSingular('Electricidad')
            ->setEntityLabelInPlural('Electricidades');
        //return parent::configureCrud($crud); // TODO: Change the autogenerated stub
    }
}
