<?php

namespace App\Controller\Admin;

use App\Entity\TypeMaterial;
use EasyCorp\Bundle\EasyAdminBundle\Config\Crud;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController;
use EasyCorp\Bundle\EasyAdminBundle\Field\IdField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextField;

class TypeMaterialCrudController extends AbstractCrudController
{
    public static function getEntityFqcn(): string
    {
        return TypeMaterial::class;
    }


    public function configureFields(string $pageName): iterable
    {
        return [
            //IdField::new('id'),
            TextField::new('name', 'Nombre'),
        ];
    }

    public function configureCrud(Crud $crud): Crud
    {
        return $crud
            ->setEntityLabelInSingular('Tipo Material')
            ->setEntityLabelInPlural('Tipo Materiales');
        //return parent::configureCrud($crud); // TODO: Change the autogenerated stub
    }

}
